version: "3.9"

services:
  redis:
    image: bitnami/valkey
    environment:
      - VALKEY_PASSWORD=password
    volumes:
      - valkey:/bitnami/valkey
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"

volumes:
  valkey: {}
