version: "3.9"

services:
  redis:
    image: bitnami/valkey
    environment:
      - VALKEY_PASSWORD=password
    volumes:
      - valkey:/bitnami/valkey
    ports:
      - "6379:6379"
  backend:
    build:
      dockerfile: ./Dockerfile
      target: app-backend
    environment:
      - REDIS_PASSWORD=password
    ports:
      - "3000:3000"
  worker1:
    build:
      dockerfile: ./Dockerfile
      target: app-worker

volumes:
  valkey: {}
