version: "3.9"

services:
  redis:
    restart: "always"
    image: bitnami/valkey
    environment:
      - VALKEY_PASSWORD=password
    volumes:
      - valkey:/bitnami/valkey
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
  backend:
    restart: "always"
    build:
      dockerfile: ./Dockerfile
      target: app-backend
    environment:
      - REDIS_PASSWORD=password
    ports:
      - "3000:3000"
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
  worker1:
    restart: "always"
    build:
      dockerfile: ./Dockerfile
      target: app-worker
    depends_on:
      - backend

volumes:
  valkey: {}
